/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ms_domwillia_jvmemory_monitor_Tagger */

#ifndef _Included_ms_domwillia_jvmemory_monitor_Tagger
#define _Included_ms_domwillia_jvmemory_monitor_Tagger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ms_domwillia_jvmemory_monitor_Tagger
 * Method:    allocateTag
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_ms_domwillia_jvmemory_monitor_Tagger_allocateTag
  (JNIEnv *, jclass, jobject, jclass);

/*
 * Class:     ms_domwillia_jvmemory_monitor_Tagger
 * Method:    getTag
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ms_domwillia_jvmemory_monitor_Tagger_getTag
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
