[package]
name = "jvmti_logger"
version = "0.1.0"
authors = ["Dom Williams <dxw405@cs.bham.ac.uk>"]
build = "build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.36"
protobuf = "1.4.3"

[build-dependencies]
protoc-rust = "1.4"
