allocations = [('alloc_object', {'id': '9235', 'type': 'java.lang.Object'}),
               ('alloc_object', {'id': '9236', 'type': 'java.lang.Integer'}),
               ('alloc_array',
                {'id': '9237', 'size': 2, 'srcArrayId': '0', 'srcIndex': 0, 'type': 'java.lang.Object[]'}),
               ('alloc_array', {'id': '9238', 'size': 2, 'srcArrayId': '0', 'srcIndex': 0, 'type': 'int[]'}),
               ('alloc_array',
                {'id': '9239', 'size': 2, 'srcArrayId': '0', 'srcIndex': 0, 'type': 'java.lang.Object[][]'}),
               ('alloc_array',
                {'id': '9240', 'size': 2, 'srcArrayId': '9239', 'srcIndex': 0, 'type': 'java.lang.Object[]'}),
               ('alloc_array',
                {'id': '9241', 'size': 2, 'srcArrayId': '9239', 'srcIndex': 1, 'type': 'java.lang.Object[]'}),
               ('alloc_array', {'id': '9242', 'size': 2, 'srcArrayId': '0', 'srcIndex': 0, 'type': 'int[][][]'}),
               ('alloc_array', {'id': '9243', 'size': 2, 'srcArrayId': '9242', 'srcIndex': 0, 'type': 'int[][]'}),
               ('alloc_array', {'id': '9244', 'size': 2, 'srcArrayId': '9243', 'srcIndex': 0, 'type': 'int[]'}),
               ('alloc_array', {'id': '9245', 'size': 2, 'srcArrayId': '9243', 'srcIndex': 1, 'type': 'int[]'}),
               ('alloc_array', {'id': '9246', 'size': 2, 'srcArrayId': '9242', 'srcIndex': 1, 'type': 'int[][]'}),
               ('alloc_array', {'id': '9247', 'size': 2, 'srcArrayId': '9246', 'srcIndex': 0, 'type': 'int[]'}),
               ('alloc_array', {'id': '9248', 'size': 2, 'srcArrayId': '9246', 'srcIndex': 1, 'type': 'int[]'})]

arrays = [('load_from_array', {'id': '9223', 'index': 0}),
          ('store_object_in_array', {'id': '9223', 'index': 1, 'valueId': '0'}),
          ('load_from_array', {'id': '9224', 'index': 0}), ('store_primitive_in_array', {'id': '9224', 'index': 1}),
          ('load_from_array', {'id': '9225', 'index': 0}), ('load_from_array', {'id': '9226', 'index': 0}),
          ('load_from_array', {'id': '9225', 'index': 1}),
          ('store_object_in_array', {'id': '9227', 'index': 1, 'valueId': '0'}),
          ('load_from_array', {'id': '9228', 'index': 0}), ('load_from_array', {'id': '9229', 'index': 0}),
          ('load_from_array', {'id': '9230', 'index': 0}), ('load_from_array', {'id': '9228', 'index': 1}),
          ('load_from_array', {'id': '9232', 'index': 1}), ('store_primitive_in_array', {'id': '9234', 'index': 1}),
          ('load_from_array', {'id': '9223', 'index': 0}), ('load_from_array', {'id': '9224', 'index': 0}),
          ('load_from_array', {'id': '9225', 'index': 0}), ('load_from_array', {'id': '9228', 'index': 0})]

callstack = [('method_enter', {'class': 'specimens.FullTest', 'method': 'testMethodCalls'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}),
             ('method_enter', {'class': 'specimens.FullTest', 'method': 'recursive'}), ('method_exit', {}),
             ('method_exit', {}),
             ('method_exit', {}), ('method_exit', {}), ('method_exit', {}), ('method_exit', {})]

definitions = ('class_def',
               {'classType': 'class',
                'fields': [{'name': 'smallPrimitive', 'static': False, 'type': 'I', 'visibility': 'private'},
                           {'name': 'largePrimitive', 'static': False, 'type': 'J', 'visibility': 'private'},
                           {'name': 'object', 'static': False, 'type': 'Ljava/lang/Object;', 'visibility': 'protected'},
                           {'name': 'constant', 'static': False, 'type': 'Ljava/lang/String;', 'visibility': 'public'},
                           {'name': 'nil', 'static': False, 'type': 'Ljava/lang/Object;', 'visibility': 'package'},
                           {'name': 'smallPrimitiveStatic', 'static': True, 'type': 'I', 'visibility': 'package'},
                           {'name': 'largePrimitiveStatic', 'static': True, 'type': 'J', 'visibility': 'package'},
                           {'name': 'objectStatic', 'static': True, 'type': 'Ljava/lang/Object;',
                            'visibility': 'package'},
                           {'name': 'constantStatic', 'static': True, 'type': 'Ljava/lang/String;',
                            'visibility': 'package'},
                           {'name': 'nilStatic', 'static': True, 'type': 'Ljava/lang/Object;',
                            'visibility': 'package'}],
                'interfaces': [],
                'methods': [
                    {'localVars': [], 'name': '<init>', 'signature': '()V', 'static': False, 'visibility': 'public'},
                    {'localVars': [],
                     'name': 'aStaticMethod',
                     'signature': '()V',
                     'static': True,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'recursive',
                     'signature': '(I)V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testMethodCalls',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testGetField',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testLocalVars',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testArrays',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testAllocations',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'testDeallocations',
                     'signature': '()V',
                     'static': False,
                     'visibility': 'package'},
                    {'localVars': [],
                     'name': 'main',
                     'signature': '([Ljava/lang/String;)V',
                     'static': True,
                     'visibility': 'public'},
                    {'localVars': [],
                     'name': '<clinit>',
                     'signature': '()V',
                     'static': True,
                     'visibility': 'package'}],
                'name': 'specimens.FullTest',
                'superClass': 'java.lang.Object',
                'visibility': 'public'})

getfield = [('get_field', {'field': 'smallPrimitive', 'id': '9218'}),
            ('get_field', {'field': 'largePrimitive', 'id': '9218'}),
            ('get_field', {'field': 'object', 'id': '9218'}), ('get_field', {'field': 'constant', 'id': '9218'}),
            ('get_field', {'field': 'nil', 'id': '9218'})]

local_vars = [('store_primitive', {'index': 1}), ('load', {'index': 1}), ('store_primitive', {'index': 2}),
              ('store_primitive', {'index': 3}), ('load', {'index': 3}), ('store_primitive', {'index': 5}),
              ('store_object', {'index': 7, 'valueId': '9221'}), ('load', {'index': 7}),
              ('store_object', {'index': 8, 'valueId': '9221'}), ('store_object', {'index': 9, 'valueId': '9222'}),
              ('load', {'index': 9}), ('store_object', {'index': 10, 'valueId': '9222'}),
              ('store_object', {'index': 11, 'valueId': '0'}), ('load', {'index': 11}),
              ('store_object', {'index': 12, 'valueId': '0'})]

putfield = [('put_field_primitive', {'field': 'smallPrimitive', 'id': '9218'}),
            ('put_field_primitive', {'field': 'largePrimitive', 'id': '9218'}),
            ('put_field_object', {'field': 'object', 'id': '9218', 'valueId': '9219'}),
            ('put_field_object', {'field': 'constant', 'id': '9218', 'valueId': '9220'}),
            ('put_field_object', {'field': 'nil', 'id': '9218', 'valueId': '0'})]
